openapi: 3.0.0
info:
  title: Shelter API
  description: シェルター情報を管理するAPI
  version: 1.0.0
# servers:
# -
#   x-amazon-apigateway-endpoint-configuration:
#     disableExecuteApiEndpoint: "true"

paths:
  # /hello:
  #   get:
  #     summary: GETサンプル
  #     description: GETのサンプルです
  #     responses:
  #       '200':
  #         description: 成功レスポンス
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Success'
  #     x-amazon-apigateway-integration:
  #       credentials:
  #         Fn::Sub: ${ApiRole.Arn}
  #       uri:
  #         Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
  #       passthroughBehavior: when_no_templates
  #       httpMethod: POST
  #       type: aws_proxy
  /shelters:
    get:
      summary: 全てのシェルターを取得
      responses:
        '200':
          description: 成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShelterList'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ShelterFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    post:
      summary: 新しいシェルターを作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShelterInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shelter'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ShelterFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy

  /shelters/{id}:
    get:
      summary: 指定IDのシェルターを取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shelter'
        '404':
          description: シェルターが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ShelterFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    put:
      summary: 指定IDのシェルターを更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShelterInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shelter'
        '404':
          description: シェルターが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ShelterFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: 指定IDのシェルターを削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 削除成功
        '404':
          description: シェルターが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ShelterFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    Shelter:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
        height:
          type: number
          format: float
      required:
        - id
        - name
        - lat
        - lng
        - height

    ShelterInput:
      type: object
      properties:
        name:
          type: string
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
        height:
          type: number
          format: float
      required:
        - name
        - lat
        - lng
        - height

    ShelterList:
      type: array
      items:
        $ref: '#/components/schemas/Shelter'

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
